name: "📝 Review 요청 (Portfolio)"
description: QA 포트폴리오 피드백을 부탁드립니다
labels: ["needs-review","portfolio","week-01"]
body:
  - type: markdown
    attributes:
      value: "summary/TC/Bug Report 링크를 확인하시고 5분 리뷰 부탁드립니다 🙏"
  - type: input
    id: focus
    attributes:
      label: Focus
      placeholder: "예: Week-01 Metal Head"
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: "Summary / Test Cases / Bug Report 링크"
      placeholder: "summary.md / test-cases.md / bug-report.md"
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: 5-min Review 체크
      options:
        - label: Severity 기준 적절
        - label: TC 커버리지 충분
        - label: Bug 카드 가독성 괜찮음
  - type: textarea
    id: comments
    attributes:
      label: Comments
      placeholder: 자유 의견
